// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52cGsu7vaY4eS6PMuRt27enwAu0PK4g0',
    appId: '1:551839504562:web:f67ea2a7d93a7ea78d91ab',
    messagingSenderId: '551839504562',
    projectId: 'ispartaapp',
    authDomain: 'ispartaapp.firebaseapp.com',
    storageBucket: 'ispartaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gOcnlT2j28dysVwN4GJjom_-_yU2_H4',
    appId: '1:551839504562:android:a70b84579622c07f8d91ab',
    messagingSenderId: '551839504562',
    projectId: 'ispartaapp',
    storageBucket: 'ispartaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHmeieVOCeVNnU7kJNJUO1Zgj1JcnG1vg',
    appId: '1:551839504562:ios:53a7f8e574eb95a78d91ab',
    messagingSenderId: '551839504562',
    projectId: 'ispartaapp',
    storageBucket: 'ispartaapp.firebasestorage.app',
    iosClientId: '551839504562-iiqb9799c6616ift2f3vtn8j1ot6dbsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ispartaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHmeieVOCeVNnU7kJNJUO1Zgj1JcnG1vg',
    appId: '1:551839504562:ios:53a7f8e574eb95a78d91ab',
    messagingSenderId: '551839504562',
    projectId: 'ispartaapp',
    storageBucket: 'ispartaapp.firebasestorage.app',
    iosClientId: '551839504562-iiqb9799c6616ift2f3vtn8j1ot6dbsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ispartaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52cGsu7vaY4eS6PMuRt27enwAu0PK4g0',
    appId: '1:551839504562:web:5d205401b2d0d0c28d91ab',
    messagingSenderId: '551839504562',
    projectId: 'ispartaapp',
    authDomain: 'ispartaapp.firebaseapp.com',
    storageBucket: 'ispartaapp.firebasestorage.app',
  );
}
